### ISSUE TITLE
Entry about LJ*

### ISSUE THREAD

**Issue by gisellemnr** [ProofSystem/Encyclopedia#60]
From "Epsilon Terms in Intuitionistic Sequent Calculus", Giselle Reis and Bruno Woltzenlogel Paleo, IfCoLog, 2016.

**Comment by ceilican** [comment]
Yes, I had this entry in mind too. Will you do it?

**Comment by gisellemnr** [comment]
Just created a pull request. Should I also add you as an author?

**Comment by ceilican** [comment]
> Just created a pull request. 

Thanks!

> Should I also add you as an author?

Only if I end up contributing to it somehow... I will have a look on it next week.
